version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/faizhasim/susunplease
    steps:
      - checkout
      - run: dep ensure
      - run: go test -v ./...
      - run: pushd cmd/susun && go build -o susun
      - run: go get github.com/faizhasim/susunplease/cmd/susun
